apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mytest-dp
  name: mytest-dp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mytest-dp
  template:
    metadata:
      labels:
        app: mytest-dp
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate: 
    maxUnavailable: 1
    maxSurge: 1
