apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-05-15T09:15:48Z"
    labels:
      app: mealie
    name: mealie
    namespace: mealie
    resourceVersion: "1530"
    uid: 62364a5b-91f2-40ba-b005-4f6d7f1a1f98
  spec:
    clusterIP: 10.43.79.25
    clusterIPs:
    - 10.43.79.25
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: mealie
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
